version: '3.8'
services:
  server:
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      NODE_ENV: 'development'
    command: yarn dev
    ports:
      - '3000:3000'
